apiVersion: v1
kind: Service
metadata:
  name: command-center-main-service
  namespace: command-center
spec:
  type: NodePort
  selector:
    app: command-center-main-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080